### PR TITLE
Fixes #20 by exposing the initial http.Request on the session

### LINKED ISSUE #20: Exposing http.Request
Is there any way the `http.Request` used to establish a SockJS connection could be exposed? I don't even need the full `Request` actually. All I really want is to be able to use path variables from the SockJS uri. For example, if my SockJS handler is wired up like:

```go
func main() {
    sockjsHandler := sockjs.NewHandler("/echo/{foo}", sockjs.DefaultOptions, echoHandler)
    http.ListenAndServe("8081", sockjsHandler)
}

func echoHandler(session sockjs.Session) {
    // I'd like to access the value of "foo" here.
}
```

Basically like how [mux.Vars](http://www.gorillatoolkit.org/pkg/mux#Vars) works.

Thoughts?

### PR DESCRIPTION
**Pull request by mweibel**
Fixes #20

### CODE REVIEW

**Comment by fatih** [comment]
Btw this broke our sockjs client which was using the session interface:

https://travis-ci.org/koding/kite/jobs/62776474

Here is the sockjsclient implementation: https://github.com/koding/kite/tree/master/sockjsclient

Because there is a new method, the clients are not compiling anymore because they do not satisfy the `sockjs.Session` interface anymore. 

I thought the point of using `gopkg.in` was to avoid such things. This PR is definitely something that breaks the exposed interface. So it should be released under the version `v3`.

**Comment by igm** [comment]
I'm sorry @fatih  , I'll revert this merge. I should have thought about this more carefully. Interface change is definitely an API change.

**Comment by igm** [comment]
Just to add, the revert happened in ```"v2"``` branch only, so that the change remains in ```"dev"``` version in ```"master"``` branch. In order to use ```"dev"``` make sure to import ```"github.com/igm/sockjs-go/sockjs"```.

**Comment by fatih** [comment]
Thanks @igm for the change.

**Comment by mweibel** [comment]
sorry @fatih @igm - not yet fully used to the golang way ;) -- @igm is there anything I'd need to do still or all ok?

**Pull request merged**
