### PR TITLE
Use Gorilla mux instead of hand-crafted mapping

### PR DESCRIPTION
**Pull request by FZambia**
Relates to #81 

@igm Just want to validate whether this is a desired change?

Notes:
1) I have not considered alternatives to `gorilla/mux` since it's popular, robust and looks nice near `gorilla/websocket`
2) I have not measured performance difference yet
3) Originally I removed requirement to pass `prefix` to SockJS handler constructor making user to use `http.StripPrefix` from outside, but then I saw that you don't want to break API globally in v3 so put prefix back to constructor

### CODE REVIEW

**Comment by FZambia** [comment]
Added `BenchmarkServe` and compared with master, unfortunately results are not very good:
```
fz@sockjs: benchstat old.txt new.txt
name     old time/op    new time/op    delta
Serve-4    1.73µs ± 2%    3.30µs ± 1%   +90.58%  (p=0.000 n=9+10)

name     old alloc/op   new alloc/op   delta
Serve-4      166B ± 3%     1442B ± 0%  +771.00%  (p=0.000 n=10+8)

name     old allocs/op  new allocs/op  delta
Serve-4      7.00 ± 0%     16.00 ± 0%  +128.57%  (p=0.000 n=10+10)
```

**Comment by FZambia** [comment]
Also experimented a bit with https://github.com/julienschmidt/httprouter - it gives better results:
```
fz@sockjs: benchstat old.txt newest.txt
name     old time/op    new time/op    delta
Serve-4    1.73µs ± 2%    1.22µs ± 4%   -29.25%  (p=0.000 n=9+9)

name     old alloc/op   new alloc/op   delta
Serve-4      166B ± 3%      663B ± 2%  +300.18%  (p=0.000 n=10+10)

name     old allocs/op  new allocs/op  delta
Serve-4      7.00 ± 0%     11.00 ± 0%   +57.14%  (p=0.000 n=10+10)
```

Faster in terms of raw operation count, but allocates a bit more. Code in separate branch: https://github.com/igm/sockjs-go/tree/httprouter, it required to handle some paths manually due to httprouter limitations and still needs some additional work for iframe, I just stopped on some point - not sure this all worth it - we can fix #81 simply modifying current mapping implementation a bit.

**Comment by igm** [comment]
@FZambia  thank you for thorough testing and benchmarking both routers, interesting results. I'll look at it more in detail.

Regarding #81 , is it still the issue in `v3` by your opinion? I thought it works fine in `v3` already. I've written a test for those cases https://github.com/igm/sockjs-go/commit/2a321445b0f6f59d66ff59322bbceb0880cad395 and they pass in `v3`.

**Comment by FZambia** [comment]
> Regarding #81 , is it still the issue in v3 by your opinion? 

Actually I missed the fact that you already fixed that in v3:)

I suppose then there is no sense to move to `mux` since it adds some overhead and no real profit for users, moving to `httprouter` could provide some performance benefit, but not too radical to go with it without additional reason.

**Pull request closed without merging**
