### PR TITLE
sockjs: add messageBuffer to get rid of internal encoding

### PR DESCRIPTION
**Pull request by rjeczalik**
This is an optimisation that reduces the memory usage of a sockjs server and client.

For previous discussion and benchmarks please see https://github.com/igm/sockjs-go/pull/56#issuecomment-287390401.

---
This change is [Reviewable](https://reviewable.io/reviews/igm/sockjs-go/63)

### CODE REVIEW

**Comment by rjeczalik** [comment]
I see there're 2 tests failing, let me look into them first. Sorry for not testing before sending PR, previous PR was passing.

**Comment by igm** [comment]
thanks for this PR (and also the #56) @rjeczalik . I started looking at it, it looks promising.

**Comment by rjeczalik** [comment]
> Why did you add 'm' frame?

I believe I've seen that frame in one of sockjs server's implementation, but I can't recall which one. I reverted that change. Please take another look.

**Comment by igm** [comment]
great, thanks for the update. I think we can merge this. The only suggestion I have is related to ```stop``` function, I think we could inline it into ```close``` so that it does not exists and also embed sync.Once

---

Reviewed 3 of 8 files at r2.
Review status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @rjeczalik and @igm)

---

*[sockjs/buffer.go, line 11 at r2](https://reviewable.io/reviews/igm/sockjs-go/63#-LG4sxoX7lMn8_K-ip-z:-LG4sxoX7lMn8_K-ip0-:bi5591z) ([raw file](https://github.com/igm/sockjs-go/blob/2bc46f31910c4332a588a7c860ba6c38a72d33f0/sockjs/buffer.go#L11)):*
> ```Go
> 	closeCh chan struct{}
> 	once    sync.Once // for b.close()
> }
> ```

```
type messageBuffer struct {
	sync.Once // for b.close()
	popCh     chan string
	closeCh   chan struct{}
}
```

---

*[sockjs/buffer.go, line 41 at r2](https://reviewable.io/reviews/igm/sockjs-go/63#-LG4hzeNCbV2aJm8Cac1:-LG4hzeNCbV2aJm8Cac2:btiyh9d) ([raw file](https://github.com/igm/sockjs-go/blob/2bc46f31910c4332a588a7c860ba6c38a72d33f0/sockjs/buffer.go#L41)):*
> ```
> func (b *messageBuffer) close() { b.Do(func() { close(b.closeCh) }) }
> ```

---

*[sockjs/buffer.go, line 42 at r2](https://reviewable.io/reviews/igm/sockjs-go/63#-LG4iBQE1CKs20j6cMFj:-LG4iBQE1CKs20j6cMFk:bi96xib) ([raw file](https://github.com/igm/sockjs-go/blob/2bc46f31910c4332a588a7c860ba6c38a72d33f0/sockjs/buffer.go#L42)):*
> ```Go
> 
> func (b *messageBuffer) close() { b.once.Do(b.stop) }
> func (b *messageBuffer) stop()  { close(b.closeCh) }
> ```

let's remove ```stop()``` and inline into ```close()``` so that it does not exist

---


*Comments from [Reviewable](https://reviewable.io/reviews/igm/sockjs-go/63#-:-LG4sSoB05oPfPPjLkXo:b-d6fcj8)*

**Comment by igm** [comment]
Reviewed 3 of 11 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @rjeczalik)

---



*Comments from [Reviewable](https://reviewable.io/reviews/igm/sockjs-go/63)*

**Comment by rjeczalik** [comment]
> let's remove stop() and inline into close() so that it does not exist

Done.

**Comment by igm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @rjeczalik)

---



*Comments from [Reviewable](https://reviewable.io/reviews/igm/sockjs-go/63#-:-LG6lTDz-mCb2BeTbjyb:bnfp4nl)*

**Comment by FZambia** [comment]
Just ran provided benchmark - on my machine it fails permanently:

```
fz@sockjs: go test -test.run=XXX -bench=BenchmarkMessageWebsocket
goos: darwin
goarch: amd64
pkg: github.com/centrifugal/centrifuge/vendor/github.com/igm/sockjs-go/sockjs
BenchmarkMessageWebsocket-4   	--- FAIL: BenchmarkMessageWebsocket-4
	benchmarks_test.go:161: WriteMessage()=write tcp 127.0.0.1:53268->127.0.0.1:53248: write: protocol wrong type for socket
	benchmarks_test.go:161: WriteMessage()=write tcp 127.0.0.1:53257->127.0.0.1:53248: write: broken pipe
FAIL
exit status 1
FAIL	github.com/centrifugal/centrifuge/vendor/github.com/igm/sockjs-go/sockjs	0.223s
```

**Comment by wavded** [comment]
I had a similar experience against master:

```
15:51 $ go test -test.run=XXX -bench=BenchmarkMessageWebsocket
goos: darwin
goarch: amd64
pkg: github.com/igm/sockjs-go/sockjs
BenchmarkMessageWebsocket-8     --- FAIL: BenchmarkMessageWebsocket-8
        benchmarks_test.go:161: WriteMessage()=write tcp 127.0.0.1:57669->127.0.0.1:57644: write: broken pipe
        benchmarks_test.go:161: WriteMessage()=write tcp 127.0.0.1:57658->127.0.0.1:57644: write: broken pipe
        benchmarks_test.go:161: WriteMessage()=write tcp 127.0.0.1:57659->127.0.0.1:57644: write: broken pipe
FAIL
exit status 1
FAIL    github.com/igm/sockjs-go/sockjs 0.122s
```

**Comment by FZambia** [comment]
Looks like the reason is session closing [at this line](https://github.com/igm/sockjs-go/blob/master/sockjs/benchmarks_test.go#L123) - client attempts to write into session that has been already closed.

**Comment by rjeczalik** [comment]
@FZambia @wavded In fact the failure is random - one in a few passes ok. I have no idea how this racy behaviour worked ok previously. I've sent a fix for it - https://github.com/igm/sockjs-go/pull/65.

**Pull request merged**
